// $Id: config.h,v 1.1 2007/04/26 13:34:02 lynx Exp $ // vim:syntax=lpc
//
// This file is not intended to be modified. Make your local changes
// in psyced.ini, and if that wasn't good enough, use local.h.
// If you are integrating psyced with other LPC applications, feel
// free to modify path.h. If you aren't, better leave it as it is.

#ifndef CONFIG_H
# define CONFIG_H

// load local modifications by the admin
# include "local.h"

// load port configuration as generated by psyconf
# include "ports.h"

// load layout of psyced software modules
# include "path.h"

// load psyced.ini settings converted by psyconf
# include "psyconf.h"

#endif
