// model '_hesmo' generated by '/home/lynx/bin/psyconf'

#define ESSENTIALS
#define PLACE_HISTORY
#define PLACE_HISTORY_EXPORT
#define PLACE_SCRATCHPAD
#define PLACE_MASQUERADE
#define PLACE_OWNED

#include "archetype.gen"
