// generated by '/home/lynx/bin/psyconf': place.i for place.gen

#ifdef PLACE_HISTORY
# define Oh "h"
#else
# define Oh ""
#endif

#ifdef PLACE_HISTORY_EXPORT
# define Oe "e"
#else
# define Oe ""
#endif

#ifdef PLACE_SCRATCHPAD
# define Os "s"
#else
# define Os ""
#endif

#ifdef PLACE_MASQUERADE
# define Om "m"
#else
# define Om ""
#endif

#ifdef PLACE_OWNED
# define Oo "o"
#else
# define Oo ""
#endif

inherit NET_PATH "place/_" Oh Oe Os Om Oo;
