/* this file shall automatically be generated by psyconf.
 *
 * the values in here may be the same as in services.h
 * or they may not. so always be conscious which ones you
 * are using to which purpose.	-lynX
 */

#echo This is just the demo ports.h. I shouldn't get loaded.
#echo If I do, then you didn't run psyconf successfully!!

#define	PSYC_PORT	4404

#define	HTTP_PORT	33333
#define	HTTPS_PORT	34443

#define	IRC_PORT	6667
#define	IRCS_PORT	9999

#define	JABBER_PORT	5222
#define	JABBERS_PORT	5223
#define	JABBER_S2S_PORT	5269

#define	TELNET_PORT	2323
#define	TELNETS_PORT	

#define	APPLET_PORT	2008

#define	SMTP_PORT	
#define	SMTPS_PORT	

#define	NTTP_PORT	
#define	NNTPS_PORT	

